# exclude: '^.*$'
fail_fast: true
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.3
  hooks:
  - id: ruff-check
    files: ^(src/|tests/).*\.py$
  - id: ruff-format
    files: ^(src/tests/).*\.py$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
    files: ^(src/|tests/).*\.py$
    additional_dependencies: [pandas-stubs, 
       types-requests, pytest-stub, types-colorama, 
       types-Pygments, types-setuptools, types-python-dateutil, 
       types-pytz]
- repo: https://github.com/fpgmaas/deptry.git
  rev: "0.23.1"
  hooks:
    - id: deptry
      pass_filenames: false
      entry: deptry src
- repo: https://github.com/netromdk/vermin
  rev: v1.7.0
  hooks:
    - id: vermin
      args: ['-t=3.9-', '--violations', '--eval-annotations', '--backport', 'typing', '--no-parse-comments']